version: "3"
services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - account-service
      - status-service
      - story-service
  db-account:
    image: mongo:4.0-xenial
    ports:
      - 27020:27017
    volumes:
      - account:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_DATABASE: root-db
  db-status:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - status:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_DATABASE: root-db
  db-story:
    image: mongo:4.0-xenial
    ports:
      - 27019:27017
    volumes:
      - story:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_DATABASE: root-db

  storyobjectdb:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --address 0.0.0.0:9000 /data
    volumes:
      - storyobjectdata:/data
  account-service:
    build: ./auth
    restart: unless-stopped
    ports:
      - 3001:3001
    depends_on:
      - db-account
    environment:
      DB_URL: mongodb://db-account/AccountDatabase

  status-service:
    build: ./post
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - account-service
      - db-status
    environment:
      DB_URL: mongodb://db-status/StatusDatabase


  story-service:
    build: ./story
    restart: unless-stopped
    ports:
      - 3003:3003
    depends_on:
      - db-story
      - account-service
      - storyobjectdb
    environment:
      DB_URL: mongodb://db-story/StoryDatabases
  
  
volumes:
  status:
  story:
  account:
  storyobjectdata:
