version: "3.7"
services:
  nginx:
    image: nahid9658/nginx
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - account-service
      - status-service
      - story-service


  db-account:
    image: mongo:4.0-xenial
    ports:
      - 27020:27017
    volumes:
      - account:/data/db
  db-status:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - status:/data/db
  db-story:
    image: mongo:4.0-xenial
    ports:
      - 27019:27017
    volumes:
      - story:/data/db
  # comment
  storyobjectdb:
        # container_name: storyobjectdb
        image: minio/minio:latest
        ports:
            - 9000:9000
            # - 9001:9001
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        command: server --console-address ":9001" /data
       
        volumes:
            - storyobjectdata:/data

  account-service:
    image: nahid9658/authservice
    build: ./backend/auth
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - db-account
    environment:
      DB_URL: mongodb://db-account:27017/account-service

  status-service: 
    build: ./backend/post
    image: nahid9658/postservice
    restart: unless-stopped
    ports:
      - 3001:3001
    depends_on:
      - account-service
      - db-status
    environment:
      DB_URL: mongodb://db-status:27017/status-service


  story-service:
    build: ./backend/story
    image: nahid9658/storyservice
    restart: unless-stopped
    ports:
      - 3002:3002
    depends_on:
      - db-story
      - account-service
      - storyobjectdb
    environment:
      DB_URL: mongodb://db-story:27017/story-service
  
  # frontend:
  #   container_name: frontend
  #   # build: ./frontend/facebook
  #   image: nahid9658/frontend
  #   restart: unless-stopped
  #   ports:
  #     - 4200:4200
  #   depends_on:
  #     - nginx
  
volumes:
  status:
  story:
  account:
  storyobjectdata:

